In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pp
import seaborn as sns
data = pd.read_csv("OneDrive/datathon/complaints.csv")

In [4]:
data.head()
for col in data.columns:
    print(col)

Date received
Product
Sub-product
Issue
Sub-issue
Consumer complaint narrative
Company public response
Company
State
ZIP code
Tags
Consumer consent provided?
Submitted via
Date sent to company
Company response to consumer
Timely response?
Consumer disputed?
Complaint ID

In [ ]:
## Preprocessing text data

In [6]:
def preprocess(ReviewText):
    ReviewText = ReviewText.str.replace("(<br/>)", "")
    ReviewText = ReviewText.str.replace('(<a).*(>).*(</a>)', '')
    ReviewText = ReviewText.str.replace('(&amp)', '')
    ReviewText = ReviewText.str.replace('(&gt)', '')
    ReviewText = ReviewText.str.replace('(&lt)', '')
    ReviewText = ReviewText.str.replace('(\\xa0)', ' ')
    ReviewText = ReviewText.str.lower()
    return ReviewText
data['Company'] = preprocess(data['Company'])
data['Company public response'] = preprocess(data['Company public response'])
data['Consumer complain narrative'] = preprocess(data['Consumer complaint narrative'])

In [7]:
data['Date received'] = pd.to_datetime(data['Date received'])
data['Date sent to company'] = pd.to_datetime(data['Date sent to company'])

In [ ]:
## Create pivots

In [8]:
prod_subprod = data.groupby(['Product', 'Sub-product'])
issue_subissue = data.groupby(['Issue', 'Sub-issue'])
date_issue = data.groupby(['Date received', 'Issue'])

In [9]:
## Product
pivot = data.pivot_table(index = ['Product'], values = ['Complaint ID'], aggfunc = 'count')
pivot.sort_values('Complaint ID', ascending = False).head(10)

                                                    Complaint ID
Product
Credit reporting, credit repair services, or ot...        365994
Mortgage                                                  298560
Debt collection                                           286996
Credit reporting                                          140432
Credit card                                                89190
Bank account or service                                    86206
Credit card or prepaid card                                71997
Checking or savings account                                60535
Student loan                                               57248
Consumer Loan                                              31604

In [11]:
## product sub product
pivot2 = data.pivot_table(index = ['Product', 'Sub-product'], values = ['Complaint ID'], aggfunc = 'count')
pivot2.sort_values('Complaint ID', ascending = False).head(10)

                                                                                               Complaint ID
Product                                            Sub-product
Credit reporting, credit repair services, or ot... Credit reporting                                  359717
Mortgage                                           Other mortgage                                     86635
                                                   Conventional fixed mortgage                        70613
Debt collection                                    I do not know                                      59638
Bank account or service                            Checking account                                   59045
Credit card or prepaid card                        General-purpose credit card or charge card         55636
Checking or savings account                        Checking account                                   45645
Debt collection                                    Other (i.e. phone, health club, etc.)              44543
                                                   Other debt                                         41973
Mortgage                                           Conventional home mortgage                         41720

In [12]:
## Issue
pivot3 = data.pivot_table(index = ['Issue'], values = ['Complaint ID'], aggfunc = 'count')
pivot3.sort_values('Complaint ID', ascending = False).head(10)

                                                    Complaint ID
Issue
Incorrect information on your report                      229316
Loan modification,collection,foreclosure                  112309
Incorrect information on credit report                    102686
Problem with a credit reporting company's inves...         82333
Loan servicing, payments, escrow account                   77333
Attempts to collect debt not owed                          63921
Cont'd attempts collect debt not owed                      60682
Improper use of your report                                43958
Communication tactics                                      39555
Managing an account                                        38075

In [14]:
## Issue & Sub-issue
pivot4 = data.pivot_table(index = ['Issue', 'Sub-issue'], values = ['Complaint ID'], aggfunc = 'count')
pivot4.sort_values('Complaint ID', ascending = False).head(10)

                                                                                                       Complaint ID
Issue                                              Sub-issue
Incorrect information on your report               Information belongs to someone else                       122191
Problem with a credit reporting company's inves... Their investigation did not fix an error on you...         59862
Incorrect information on your report               Account status incorrect                                   37555
Incorrect information on credit report             Account status                                             37057
Cont'd attempts collect debt not owed              Debt is not mine                                           36727
Incorrect information on your report               Account information incorrect                              34147
Attempts to collect debt not owed                  Debt is not yours                                          33236
Incorrect information on credit report             Information is not mine                                    32384
Improper use of your report                        Credit inquiries on your report that you don't ...         29636
Written notification about debt                    Didn't receive enough information to verify debt           23158

In [15]:
pivot = data.pivot_table(index = ['Product','Issue'], values = ['Complaint ID'], aggfunc = 'count')
pivot.sort_values('Complaint ID', ascending = False).head(10)

                                                                                                       Complaint ID
Product                                            Issue
Credit reporting, credit repair services, or ot... Incorrect information on your report                      221851
Mortgage                                           Loan modification,collection,foreclosure                  112309
Credit reporting                                   Incorrect information on credit report                    102686
Credit reporting, credit repair services, or ot... Problem with a credit reporting company's inves...         79673
Mortgage                                           Loan servicing, payments, escrow account                   77333
Debt collection                                    Attempts to collect debt not owed                          63921
                                                   Cont'd attempts collect debt not owed                      60682
Credit reporting, credit repair services, or ot... Improper use of your report                                42963
Debt collection                                    Communication tactics                                      39555
Checking or savings account                        Managing an account                                        38075